const menu = [
    {
      id: 1,
      title: 'buttermilk pancakes',
      category: 'breakfast',
      price: 15.99,
      img: 'https://simplyhomecooked.com/wp-content/uploads/2022/08/buttermilk-pancakes-2.jpg',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 2,
      title: 'diner double',
      category: 'lunch',
      price: 13.99,
      img: 'https://media-cdn.tripadvisor.com/media/photo-s/1a/86/9d/db/canada-s-diner-double.jpg',
      desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
    },
    {
      id: 3,
      title: 'godzilla milkshake',
      category: 'shakes',
      price: 6.99,
      img: 'https://i2-prod.glasgowlive.co.uk/incoming/article16335490.ece/ALTERNATES/s810/0_DSC_5334-copy-1.jpg',
      desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
    },
    {
      id: 4,
      title: 'country delight',
      category: 'breakfast',
      price: 20.99,
      img: 'https://countrygirlrestaurant.ca/wp-content/uploads/2014/07/Social-Media-Files_036.jpg',
      desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
    },
    {
      id: 5,
      title: 'egg attack',
      category: 'lunch',
      price: 22.99,
      img: 'https://domf5oio6qrcr.cloudfront.net/medialibrary/12027/d02feeb0-8e73-48fb-946f-5c01d1813a41.png',
      desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
    },
    {
      id: 6,
      title: 'oreo dream',
      category: 'shakes',
      price: 18.99,
      img: 'https://www.lifeloveandsugar.com/wp-content/uploads/2018/09/Ultimate-Oreo-Cheesecake3.jpg',
      desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    },
    {
      id: 7,
      title: 'bacon overflow',
      category: 'breakfast',
      price: 8.99,
      img: 'https://scontent.fpat6-1.fna.fbcdn.net/v/t1.18169-9/10168096_738325649520996_8923736257688211838_n.jpg?_nc_cat=106&ccb=1-7&_nc_sid=9267fe&_nc_ohc=A45r0l92zLgAX9Y0yzR&_nc_ht=scontent.fpat6-1.fna&oh=00_AfAFSZKC2r8yQ3FwDdp_QSclnwqMFthoK9UmoUo-n7IEXw&oe=64188FC1',
      desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
    },
    {
      id: 8,
      title: 'american classic',
      category: 'lunch',
      price: 12.99,
      img: 'https://img.theculturetrip.com/wp-content/uploads/2017/05/nathans.jpg',
      desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
    },
    {
      id: 9,
      title: 'quarantine buddy',
      category: 'shakes',
      price: 16.99,
      img: 'http://www.kepakfoodservice.ie/wp-content/uploads/2020/04/Email-HelpfulTips-3-hot-date-4.jpg',
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
  ];
  export default menu;